### ISSUE TITLE
Create Invitation Codes index page.

### ISSUE THREAD

**Issue by mgurley** [NUBIC/all-of-us-helper#8]

**Comment by firaswehbe** [comment]
How would this work? Shows all the unassigned codes? Or will it show all codes with strike through or something like that to show when they were assigned and to whom?

**Comment by mgurley** [comment]
Each code will have an assignment status: Unassigned/Assigned.  The index page will be able to be filtered by assignment status.  Defaulting to 'Unassigned'.  Codes with an 'Assigned' status will display the patient assigned to the code and the assignment date.  'Unassigned' codes will have a blank patient/assignment date.  I don't see the user using this page all that often, but it is necessary to have when they need to look at their 'Code' inventory.

**Comment by mgurley** [comment]
Most of the work will be done by the cron job querying for patients in REDCap without an invitation code, creating a patient locally,  taking an unassigned invitation code from the inventory,  pushing the invitation code to REDCap and marking it as assigned in Helper (my nickname for this application).
  If the user want's to manually assign a code, the REDCap project will link to a new code assignment page with this URL /patients/:record_id/code_assignments/new.  If the record_id does not exist (before the Cron job interval), it will call the REDCap API to get patient's details and insert a row into the patients table.  
If the record_id exists and the patient already has an invitation code, the page will display the patients current invitation code.  Either way the page will display the patient's details, pull an available 'Unassigned' code and present it to user to save.  If the user saves, the new invitation code will be pushed to REDCap.  In Helper, we will keep track of all the invitation codes ever assigned to a patient and mark the last recently pushed code to REDCap as 'Active' and all others as 'Inactive'.
